version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cercadeti-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cercadeti_dev
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapi -d cercadeti_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
