import type { Business, BusinessWithDetails, Category, Zone, BusinessPlan } from '@/types';

// Mock zone
const mockZone: Zone = {
  id: '1',
  name: 'Pedregal',
  slug: 'pedregal',
  description: 'Zona Pedregal',
  is_active: true,
  created_at: new Date().toISOString(),
};

// Mock plan
const mockPlan: BusinessPlan = {
  id: '1',
  name: 'Plan Básico',
  description: 'Plan básico para negocios',
  price_monthly: 0,
  features: [],
  max_images: 5,
  featured: false,
  priority: 1,
  created_at: new Date().toISOString(),
};

// Category mapper
const categoryMap: Record<string, Category> = {
  'Restaurantes': {
    id: '1',
    name: 'Restaurantes',
    slug: 'restaurantes',
    icon: 'Utensils',
    color: '#FF6B6B',
    description: 'Los mejores restaurantes de la zona',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'Supermercados': {
    id: '2',
    name: 'Supermercados',
    slug: 'supermercados',
    icon: 'ShoppingCart',
    color: '#4ECDC4',
    description: 'Supermercados y tiendas de abarrotes',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'Servicios Hogar': {
    id: '3',
    name: 'Servicios Hogar',
    slug: 'servicios-hogar',
    icon: 'Home',
    color: '#95E1D3',
    description: 'Servicios para tu hogar',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'Mascotas': {
    id: '4',
    name: 'Mascotas',
    slug: 'mascotas',
    icon: 'Dog',
    color: '#F38181',
    description: 'Todo para tus mascotas',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'Transporte': {
    id: '5',
    name: 'Transporte',
    slug: 'transporte',
    icon: 'Car',
    color: '#AA96DA',
    description: 'Servicios de transporte',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'Salud': {
    id: '6',
    name: 'Salud',
    slug: 'salud',
    icon: 'Heart',
    color: '#FCBAD3',
    description: 'Servicios de salud y bienestar',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'Belleza': {
    id: '7',
    name: 'Belleza',
    slug: 'belleza',
    icon: 'Sparkles',
    color: '#FFFFD2',
    description: 'Salones de belleza y estética',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'Deportes': {
    id: '8',
    name: 'Deportes',
    slug: 'deportes',
    icon: 'Dumbbell',
    color: '#A8D8EA',
    description: 'Gimnasios y deportes',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'Educación': {
    id: '9',
    name: 'Educación',
    slug: 'educacion',
    icon: 'GraduationCap',
    color: '#FFB6C1',
    description: 'Servicios educativos',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'Entretenimiento': {
    id: '10',
    name: 'Entretenimiento',
    slug: 'entretenimiento',
    icon: 'Tv',
    color: '#DDA0DD',
    description: 'Entretenimiento y ocio',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'Fotografía': {
    id: '11',
    name: 'Fotografía',
    slug: 'fotografia',
    icon: 'Camera',
    color: '#F0E68C',
    description: 'Servicios fotográficos',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'Moda': {
    id: '12',
    name: 'Moda',
    slug: 'moda',
    icon: 'Shirt',
    color: '#FFE4E1',
    description: 'Moda y ropa',
    is_active: true,
    created_at: new Date().toISOString(),
  },
};

export function businessToBusinessWithDetails(business: Business): BusinessWithDetails {
  const category = categoryMap[business.category] || categoryMap['Restaurantes'];

  return {
    id: business.id,
    name: business.name,
    description: business.description,
    category_id: category.id,
    zone_id: mockZone.id,
    plan_id: mockPlan.id,
    email: business.email,
    phone: business.phone,
    website: business.website,
    address: business.address,
    main_image_url: business.image,
    gallery_urls: [],
    hours: business.hours,
    rating: business.rating,
    review_count: 0,
    featured: business.featured,
    offer: business.offer,
    offer_text: business.offer ? '¡Oferta especial!' : undefined,
    is_active: true,
    is_verified: true,
    supports_delivery: true,
    delivery_time: business.deliveryTime,
    delivery_fee: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category,
    zone: mockZone,
    plan: mockPlan,
  };
}
